services:
  - type: web
    name: qurgon-ish-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: 8963697303:AAFmbHY8dtcPOeTUiGpTZveSiFq-9lYxV6M
      - key: ADMIN_ID
        sync: 8530025653
